
CBLITE_URL = "http://localhost:59840"
CBLITE_NAME = "test"


COUCHDB_URL = "http://localhost:5984/"
COUCHDB_NAME = "test"
COUCHDB_NAME2 = "test2"

COUCHDB_SYNC_URL = "http://localhost:4984"
COUCHDB_SYNC_ADMIN_URL = "http://localhost:4985"

COUCHBASE_BUCKET = "test_bucket"
COUCHBASE_LOCAL_URL = "http://127.0.0.1:8091"
COUCHBASE_HOST = "127.0.0.1"
COUCHBASE_PORT = "8091"
COUCHBASE_ADMIN = "paul"
COUCHBASE_ADMIN_PASSWORD = "mouse99"
